#!/bin/bash

./space_calc.sh "/Library/Caches"
./space_calc.sh "/Library/Logs"
./space_calc.sh "/Library/Updates"
./space_calc.sh "~/Library/Caches"
./space_calc.sh "~/Library/Logs"
./space_calc.sh "~/Library"
./space_calc.sh "~/Library/Application Support"
./space_calc.sh "~/Library/Developer/Xcode/DerivedData"
./space_calc.sh "/var/log"
./space_calc.sh "/private/var/folders"
./space_calc.sh "/Library/Application Support"
./space_calc.sh "/Library/Preferences"
./space_calc.sh "/Library/Developer/Xcode/DerivedData"
./space_calc.sh "/Library/Caches/com.apple.dt.Xcode"

echo "搜尋可刪目錄"
./lschildren.sh "/Library/Caches"
./lschildren.sh "/Library/Application Support"
./lschildren.sh "/Library/Preferences"

echo "刪除暫存檔案"
rm -r "/Library/Logs/*"
rm -r "/Library/Updates/*"
rm -r "/var/log/*"
rm -r "/private/var/folders/*"
